"""
report.py — Generates output files from analysis.
Takes analysis dictionary → creates JSON and Markdown files.
No API calls happen here — just file writing.
"""

import json
import os
from datetime import datetime


# ─── File Saving Functions ───────────────────────────────────────────────────

def save_json(analysis: dict) -> str:
    """
    Saves analysis dictionary as JSON file.
    Returns the file path where it was saved.
    """
    os.makedirs("outputs", exist_ok=True)

    file_path = "outputs/analysis.json"

    with open(file_path, "w") as f:
        json.dump(analysis, f, indent=2)

    return file_path


def save_markdown(analysis: dict) -> str:
    """
    Generates markdown report and saves it as .md file.
    Returns the file path where it was saved.
    """
    os.makedirs("outputs", exist_ok=True)

    file_path = "outputs/report.md"

    md_content = generate_markdown(analysis)

    with open(file_path, "w", encoding="utf-8") as f:
        f.write(md_content)

    return file_path


# ─── Markdown Generator ──────────────────────────────────────────────────────

def generate_markdown(analysis: dict) -> str:
    """
    Converts analysis dictionary into
    a human readable markdown string.
    """
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    scores = analysis["scores"]
    overall = analysis["overall"]
    problem = analysis["problem_statement"]
    solution = analysis["proposed_solution"]
    innovation = analysis["core_innovation"]
    market = analysis["market_landscape"]
    support = analysis["support_required"]
    tech = analysis["tech_stack"]

    md = f"""# 🚀 Startup Idea Validation Report
Generated: {timestamp}
Founder: {analysis["founder_name"]}
Idea: {analysis["idea_summary"]}

---

## 1️⃣ Problem Statement
- **Description:** {problem["description"]}
- **Target Audience:** {problem["target_audience"]}
- **Why Current Solutions Fail:** {problem["why_current_solutions_fail"]}

---

## 2️⃣ Proposed Solution
- **What is Built:** {solution["what_is_built"]}
- **How it Solves:** {solution["how_it_solves"]}

---

## 3️⃣ Core Innovation
- **Uniqueness:** {innovation["uniqueness"]}
- **Innovation Type:** {innovation["innovation_type"]}

---

## 4️⃣ Market Landscape
- **Similar Solutions:** {market["similar_solutions"]}
- **Competition Level:** {market["competition_level"]}
- **Market Gap:** {market["market_gap"]}

---

## 5️⃣ Scores (1-10)
| Category | Score | Reasoning |
|----------|-------|-----------|
| Market Feasibility | {scores["market_feasibility"]["score"]}/10 | {scores["market_feasibility"]["reasoning"]} |
| Marketing Potential | {scores["marketing_potential"]["score"]}/10 | {scores["marketing_potential"]["reasoning"]} |
| Scalability | {scores["scalability"]["score"]}/10 | {scores["scalability"]["reasoning"]} |
| Revenue Potential | {scores["revenue_potential"]["score"]}/10 | {scores["revenue_potential"]["reasoning"]} |
| Technical Complexity | {scores["technical_complexity"]["score"]}/10 | {scores["technical_complexity"]["reasoning"]} |
| Execution Risk | {scores["execution_risk"]["score"]}/10 | {scores["execution_risk"]["reasoning"]} |

---

## 6️⃣ Support Required
- **Team Needed:** {support["team_needed"]}
- **Funding Stage:** {support["funding_stage"]}
- **Partnerships:** {support["partnerships"]}
- **Regulatory:** {support["regulatory"]}

---

## 7️⃣ Tech Stack
- **Backend:** {tech["backend"]}
- **Frontend:** {tech["frontend"]}
- **Database:** {tech["database"]}
- **Cloud:** {tech["cloud"]}
- **AI Tools:** {tech["ai_tools"]}

---

## 8️⃣ Overall Verdict
- **Overall Score:** {overall["score"]}/10
- **MVP Ready:** {overall["is_mvp_ready"]}
- **Investment Ready:** {overall["is_investment_ready"]}
- **Incubator Ready:** {overall["is_incubator_ready"]}

### Final Verdict
{overall["final_verdict"]}

---
*Report generated by ThynxAI Idea Lab*
"""
    return md